notifications:
  email: false

language: cpp

before_script:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
script: bash ./.travis_script.sh build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: doc
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./.travis_script.sh deploy
